---
abstract: 'Plugin-based @INC mangling'
author:
  - 'Peter Shangov <pshangov@yahoo.com>'
build_requires:
  Data::Dump: 0
  File::Find: 0
  File::Slurp: 0
  File::Temp: 0
  File::chdir: 0
  Test::More: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: lib-ini
requires:
  Class::Load: 0
  Config::INI::Reader: 0
  File::Spec: 0
  String::RewritePrefix: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=lib-ini
  homepage: https://github.com/pshangov/lib-ini
  repository: https://github.com/pshangov/lib-ini.git
version: 0.002
